openapi: 3.0.3
info:
  title: Chaos Lab Fault Proxy
  version: 1.0.0
servers:
  - url: /
paths:
  /chaos-fetch:
    get:
      summary: Proxy HTTP fetch with optional latency/errors
      parameters:
        - in: query; name: url; required: true; schema: { type: string }
        - in: query; name: delay_ms; schema: { type: integer, minimum: 0 }
        - in: query; name: fault; schema: { type: string, enum: [http_500, rate_limit_429, none] }
        - in: query; name: rate; schema: { type: number, minimum: 0, maximum: 1 }
        - in: query; name: seed; schema: { type: string }
      responses: { "200": { description: "OK" }, "429": { description: "Rate limited" }, "500": { description: "Injected error" } }
  /chaos-json:
    get:
      summary: Fetch JSON and optionally return malformed payload
      parameters:
        - in: query; name: url; required: true; schema: { type: string }
        - in: query; name: malformed_rate; schema: { type: number, minimum: 0, maximum: 1 }
        - in: query; name: delay_ms; schema: { type: integer, minimum: 0 }
        - in: query; name: seed; schema: { type: string }
      responses: { "200": { description: "OK (maybe malformed)" } }
  /chaos-rag:
    get:
      summary: Return doc chunks, with optional benign prompt-injection or truncation
      parameters:
        - in: query; name: inj_seed; schema: { type: string }
        - in: query; name: ctx_bytes; schema: { type: integer, minimum: 0 }
        - in: query; name: seed; schema: { type: string }
      responses: { "200": { description: "OK" } }